#!/bin/sh

for degauss in  0.01 0.03  
do
for  nk  in 6 8
do 

cat > input.pw <<EOF
 &control
    calculation = 'scf',
    prefix = 'al',
    pseudo_dir = '../../../pseudo',
    outdir = './tmp'
 /
 &system
    ibrav =  2, 
    celldm(1) = 7.461, 
    nat =  1, 
    ntyp = 1,
    nbnd = 10
    ecutwfc = 16,
    occupations='smearing'
    smearing='methfessel-paxton'
    degauss=$degauss
 /
 &electrons
    mixing_beta = 0.7
 /
ATOMIC_SPECIES
Al  26.98 Al.pz-vbc.UPF
ATOMIC_POSITIONS (alat)
 Al 0.0 0.0 0.0
K_POINTS (automatic)
  $nk $nk $nk 1 1 1

EOF


/home/fmohamed/Desktop/2023-2024/ASESMA2023/qe-7.2/bin/pw.x -inp input.pw |tee out.al.${degauss}.${nk}.mp
grep -e ! out.al.${degauss}.${nk}.gauss |  awk '{print $5}' > etot
echo $degauss  $nk $etot >> al.etot_vs_ecut
done
done
